#!/usr/bin/env python
#
# This bin script is intended only for testing.
# It will not be used by the installed egg.
#
# For testing, just put the path to this bin script ahead of all
# others, e.g.:
# export PATH=/path/to/gitifyhg/bin:$PATH

import os
import sys

# Set up sys.path so our package is before all others
# (including eggs of ourselves that have been installed).
bindir = os.path.dirname(__file__)
sys.path.insert(1, os.path.abspath(os.path.join(bindir, "..")))

from gitifyhg import gitifyhg
gitifyhg.main()
